### ISSUE TITLE
PHPStan extension for apply-filters-typed

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/phpstan-apply-filters-typed#1]

**Comment by MathieuLamiot** [comment]
@Miraeld @remyperona Should this be closed as a duplicate of https://github.com/wp-media/wp-rocket/issues/7120?

**Comment by MathieuLamiot** [comment]
@Miraeld @remyperona Kind reminder :)

**Comment by remyperona** [comment]
yes
